# Form implementation generated from reading ui file 'devview.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
from colorama import init
init()
from colorama import Fore, Back, Style

print("  > Initializing Dev View")
print("")

print(Back.RED + 'DO NOT CLOSE THIS WINDOW!')
print(Style.RESET_ALL)



saver = open("files/savers/1.saver", "r")
file1 = saver.read()
saver = open("files/savers/2.saver", "r")
file2 = saver.read()
saver = open("files/savers/3.saver", "r")
file3 = saver.read()
saver = open("files/savers/1.saver", "r")

file1 = (file1.replace("\\", '/', 10))
file2 = (file2.replace("\\", '/', 10))
file3 = (file3.replace("\\", '/', 10))

def onClick1(checked):
    os.startfile(file1)
    print("  > Opening file in external application", file1)
def onClick2(checked):
    os.startfile(file2)
    print("  > Opening file in external application", file2)
def onClick3(checked):
    os.startfile(file3)
    print("  > Opening file in external application", file3)



print("  > Recent files loaded")
print("  > Loading window")

print('    ____                 _    ___ ')
print('   / __ \___ _   __     | |  / (_)__ _      __')
print('  / / / / _ \ | / /     | | / / / _ \ | /| / /')
print(" / /_/ /  __/ |/ /      | |/ / /  __/ |/ |/ / ")
print("/_____/\___/|___/       |___/_/\___/|__/|__/ ")
print("Dev View, Part of VKode software budnle, (c) Vít Kozel, 2021. https://twitter.com/vkode_")

print("")
print(Back.RED + 'DO NOT CLOSE THIS WINDOW!')
print(Style.RESET_ALL)
print("")
print("")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 140, 751, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 180, 751, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 120, 75, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(onClick1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 160, 75, 24))
        self.pushButton_2.clicked.connect(onClick1)
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 190, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(onClick3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setProperty("Exit", "")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VKode Dev View"))
        self.label.setText(_translate("MainWindow", "Dev View"))
        self.label_2.setText(_translate("MainWindow", file1))
        self.label_3.setText(_translate("MainWindow", file2))
        self.label_4.setText(_translate("MainWindow", file3))
        self.pushButton.setText(_translate("MainWindow", "OPEN"))
        self.pushButton_2.setText(_translate("MainWindow", "OPEN"))
        self.pushButton_3.setText(_translate("MainWindow", "OPEN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
